### ISSUE TITLE
Remove the special case for 'xmlhttprequest' in the include processor

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#2455]
I did some tests on the Chrome/Firefox extension and the following include target are working without this special case.

Please note that `base_dir` needs to be defined.
`Opal.current_dir` (used in `Dir.pwd`) can also be defined but that's not mandatory.
https://github.com/opal/opal/blob/a71e77b87c334096285dd597bd6c6a4d9a9d60e7/opal/corelib/dir.rb#L11-L13

#### Firefox

`base_dir` attribute is equals to `file:///home/guillaume/asciidoctor`.

* `include::./b.adoc[]` → **OK**
* `include::b.adoc[]` → **OK**
* `include::/home/guillaume/asciidoctor/b.adoc[]` → Firefox  throws an `SyntaxError: "The URI is malformed.` (1)
* `include::file:///home/guillaume/Documents/asciidoctor/b.adoc[]` → the attribute `allow-uri-read` needs to be defined

(1) In Asciidoctor.js, we could catch this exception, add the protocol and try to read the file again. Or we could proactively transform the include target to add the protocol if we are running in Firefox.

#### Chrome

* `include::./b.adoc[]` → **OK**
* `include::b.adoc[]` → **OK**
* `include::/home/guillaume/asciidoctor/b.adoc[]` → **OK**
* `include::file:///home/guillaume/Documents/asciidoctor/b.adoc[]` → the attribute `allow-uri-read` needs to be defined

### `http(s)://` protocol

`http(s)://` paths are not considered as absolute paths for the `is_root` method:

https://github.com/asciidoctor/asciidoctor/blob/a9dc0e23cd49ca428206ed5f29a0be0f9095ee02/lib/asciidoctor/path_resolver.rb#L144-L148

So the following exception is thrown: `Jail is not an absolute path: ...`

**Comment by Mogztter** [comment]
Opal is making good progress on implementing I/O methods but the downside is that Ruby I/O methods are designed to work on paths (not on URI).
For instance `File.join` will append a leading slash:

```ruby
p File.join('', 'http://localhost:9876/base/build/css') # "/http://localhost:9876/base/build/css"
```

@mojavelinux Do you think it's safe to assume that `http(s)://` URI are absolute paths in the `is_root` method ?

**Comment by Mogztter** [comment]
I've added tests in Asciidoctor.js to avoid regressions. I've also written an "include macro support" to give a synthetic view:

https://github.com/Mogztter/asciidoctor.js/blob/721335bd6f3c834aaa41f24f66e38b646cdd3539/include-support.adoc

I still need to add Nashorn and XMLHttpRequest/Firefox in this table.

I don't think we should spend too much time on Rhino or SpiderMonkey because I believe that the usage is very low. And since the development of PhantomJS is not active anymore, I think it's safe to focus on browsers' headless mode.

**Comment by mojavelinux** [comment]
Just thinking out loud here, I wonder if we need to also implement logic like [file-uri-to-path](https://yarnpkg.com/en/package/file-uri-to-path).

**Comment by Mogztter** [comment]
> Just thinking out loud here, I wonder if we need to also implement logic like file-uri-to-path.

It could be a good idea.
We just need to be careful about where and when we use this logic 😉

**Comment by mojavelinux** [comment]
> I don't think we should spend too much time on Rhino or SpiderMonkey because I believe that the usage is very low.

Agreed. The environments that really matter are:

* Node
* Nashorn
* Browser (for the browser extension)

**Comment by mojavelinux** [comment]
There's a lot to process here, so I want to take it one bit at a time. Let's start with the xmlhttprequest exception in the reader.

If I'm remembering correctly, this logic was implemented to try to auto-configure Asciidoctor.js to handle includes (in particular, top-level includes). The logic is as follows:

* assume that Asciidoctor.js does not explicitly set the `:base_dir` option or `docdir` attribute
* as a result, the `@base_dir` property on document will get set to ::Dir.pwd (an assumption we broke since expand_path is now run on this value)
* when processing a top-level include (i.e., the include stack is empty), and the `@base_dir` property matches ::Dir.pwd exactly, use the value of target as is.

I'm afraid since then we've broken some of these assumptions. So I think it's time to revisit the logic.

Perhaps what we should say is that if this is a top-level include (i.e, the include stack is empty), we prepend the `@base_dir` property. Full stop.

Also, we should not run expand_path on the `:base_dir` option if we're in the browser (unless you think the browser implementation for expand_path can just ignore that request).

**Comment by mojavelinux** [comment]
Backing up for a second, it's very safe to say that Asciidoctor.js in the browser was optimized for the base_dir option *not* being set. In that case, the `@base_dir` property on document and Dir.pwd end up being the same value (`.`), which allows the XMLHttpRequest to request the relative target.

I think were we start to get the problem is when the target is not relative.

**Comment by mojavelinux** [comment]
> Do you think it's safe to assume that http(s):// URI are absolute paths in the is_root method ?

In the xmlhttprequest environment, yes.

**Comment by mojavelinux** [comment]
The more I think about this, the more I think we need to keep the exception, but just improve it.

It's very risky to let browser fs paths pass through the same logic as a normal fs path because these two need to be handled in fundamentally different ways.

What we need to do is make sure that if the target is absolute (whether it begins with a URI scheme or its an absolute fs path), the value needs to be preserved. I think that then allows all cases to work properly.

**Comment by mojavelinux** [comment]
I've thought about it even more and I'm convinced we need to keep this logic separate. Even if we end up doing most of the same logic that's in the next block (where the resolved target is uriish), the semantics are different. I'm going to focus on supporting all the cases that are currently not handled by the existing block.

Here's the list I'm working on (all in the xmlhttprequest environment):

* PathResolver#is_root? should return `true` if the path begins with http:// or https:// (in addition to file://, which is already supported)
* if the target of any include is an absolute URI, use it as is
* if the target of any include is an absolute fs path, prepend the file:// scheme
  * there must be three forward slashes in front of the drive letter on Windows (e.g., `file:///C:/...`)
* if the target of a top-level include is relative, and base_dir does not equal `.`, prepend the base_dir
  * @Mogztter I know you were concerned about path joining here; can we simply join on `/` or should the logic be more sophisticated?
  * should expand `..` segments in the resolved URI?

An open question is whether we should require allow-uri-read to be set if the resolved target of a top-level include is not a derivative of base_dir. Or does the same-origin policy of the browser already protect against this?

**Comment by mojavelinux** [comment]
I plan to make a 1.5.6.2 release that includes these changes. That allows us to release Asciidoctor.js 1.5.6 before Asciidoctor 1.5.7 is ready (plus it gives us a stable 1.5.6 release for Asciidoctor.js).

**Comment by Mogztter** [comment]
> PathResolver#is_root? should return true if the path begins with http:// or https:// (in addition to file://, which is already supported)

✔️ 

> Don't expand value of :base_dir option if running PathResolver#is_root? on the value returns true

💡  You may want to use `expand_path` to expand `..` in an absolute path (for instance `/home/guillaume/../dan` -> `/home/dan`). But we should definitely not use it on path with a protocol.

> if the target of any include is an absolute URI, use it as is

✔️ 

> if the target of any include is an absolute fs path, prepend the file:// scheme
> there must be three forward slashes in front of the drive letter on Windows (e.g., file:///C:/...)
> we may need another method to check for an absolute path which does not include URI schemes

✔️ but we need to be careful here because I do have the feeling that it can produce side effects 💥 

> if the target of a top-level include is relative, and base_dir does not equal ., prepend the base_dir
> * @Mogztter I know you were concerned about path joining here; can we simply join on / or should the logic be more sophisticated?
> * should expand .. segments in the resolved URI?

💡 As you said, I think we can start by doing a simple join on `/` and then improve the logic if we need to.

**Comment by mojavelinux** [comment]
The :soccer: is rolling.

**Comment by mojavelinux** [comment]
Btw, I have started a branch for the 1.5.6.2 patch release. See https://github.com/asciidoctor/asciidoctor/tree/v1.5.6.x.

**Comment by mojavelinux** [comment]
> Don't expand value of :base_dir option if running PathResolver#root? on value returns true

In the end, I don't actually think this exception is needed. Long term, we either want a real fix in #2592 or you can set the docdir attribute from the API, which is taken as is. We can always remove this exception before 1.5.7. The focus right now, however, is to get a 1.5.6 version that allows us to release Asciidoctor.js 1.5.6 final.

**Comment by mojavelinux** [comment]
I also noticed that we'll need special logic in PathResolver to detect a Windows drive root when working in the browser. We can't assume that the file separator is backslash as it won't be.

**Comment by mojavelinux** [comment]
> include::/home/guillaume/asciidoctor/b.adoc[] → Firefox throws an SyntaxError: "The URI is malformed."

I'm not seeing this error. Perhaps it's fixed in a newer version of Firefox?

**Comment by Mogztter** [comment]
> I'm not seeing this error. Perhaps it's fixed in a newer version of Firefox?

That would be nice but I can still see this error in the browser extension using Firefox 58.0.2.
How are you testing this issue ?

**Comment by mojavelinux** [comment]
Oh, I see. This might just happen when running inside an extension. I've been manual testing with a standalone page. Something like:

```html
<div id="content"></div>
<script src="../build/asciidoctor.js"></script>
<script>
var asciidoctor = Asciidoctor()
var target = 'inc/message.adoc'
var html = asciidoctor.convert('include::' + target + '[]', {
  safe: 'safe',
  base_dir: Opal.File.$dirname(window.location.href),
  //attributes: 'allow-uri-read',
})
document.getElementById('content').innerHTML = html
</script>
```

**Comment by mojavelinux** [comment]
I'm pretty sure #2603 is ready for testing.

**Comment by mojavelinux** [comment]
This has now been resolved. Better yet, control has been handed over to Asciidoctor.js, so it can now control its own destiny!

See PreprocessorReader#resolve_include_path.

Whether we decide to keep the special case for the xmlhttprequest IO module or allow it to fall through and be handled like all other environments is still up for debate. However, I think the following document makes it clear that until we have first-class support for using a URI as a base_dir, we need the exception. https://github.com/asciidoctor/asciidoctor.js/blob/master/docs/asciidoctor-browser-include-spec.adoc
